config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  devise_for :workers
  devise_for :customers
  resources :skills, only: [:index]
  resources :workers, only: [:index]
  get 'skills/search', to: 'skills#search'
  get 'workers/customer/:id', to: 'workers#customer', via: :get, as: :workers_customer
  get 'workers/skill', to: 'workers#skill', via: :get, as: :workers_skill
  root 'skills#index'

end

app/models/customer.rb
class Customer < User
  has_and_belongs_to_many :workers, join_table: :customers_workers
end

app/models/skill.rb
class Skill < ActiveRecord::Base
  has_and_belongs_to_many :workers, join_table: :workers_skills
  validates_uniqueness_of :name
  paginates_per 5
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  def worker?
    self.type == 'Worker'
  end

  def customer?
    self.type == 'Customer'
  end
end

app/models/worker.rb
class Worker < User
  has_and_belongs_to_many :skills, join_table: :workers_skills
  has_and_belongs_to_many :customers, join_table: :customers_workers
  paginates_per 3

  def image_url
    "https://robohash.org/#{self.email}?set=set2&size=80x80"
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  def current_user
    current_worker || current_customer
  end

  def auth_user!(opts = {})
    if customer_signed_in?
      authenticate_customer!
    else
      authenticate_worker!
    end
  end
end

app/controllers/skills_controller.rb
class SkillsController < ApplicationController
  before_action :auth_user!, :except => [:index]

  def index
   @skills = Skill.all.page skills_params[:page]
  end

  def search
    @skills = paginate_skills
  end

  private

  def paginate_skills
    #TODO: add per_page as a config thing
    skills.page skills_params[:page]
  end

  def skills
    Search::SkillFinder.find(keywords: keywords)
  end

  def skills_params
    @_skills_params ||= params.permit(:page, :keywords)
  end

  def keywords
    skills_params[:keywords].split(',') if skills_params[:keywords]
  end
end

app/controllers/workers_controller.rb
class WorkersController < ApplicationController
  before_action :auth_user!

  def index
    if customer_searching?
      @workers = workers
    end
    render 'index', layout: false
  end

  def customer
    worker = Worker.find(worker_id_params)
    render_not_found and return if !worker
    worker.customers << current_user
    render_worker_save(worker, worker.email)
  end

  def skill
    worker = current_worker
    render_not_found and return if !worker
    skill = Skill.find_or_create_by(name: workers_params[:skill])
    worker.skills << skill if skill
    render_worker_save(worker, skill.name)
  rescue ActiveRecord::RecordNotUnique
    render_error(worker)
  end

  def render_not_found
    render(text: "404 Not Found", status: 404)
  end

  private

  def workers
    Search::WorkerWithSkillFinder.find(keywords: keywords)
      .page workers_params[:workers_page]
  end

  def customer_searching?
    workers_params[:keywords] && current_user.customer?
  end

  def worker_id_params
    params.permit(:id)[:id]
  end

  def workers_params
    @_workers_params ||= params.permit(:workers_page, :keywords, :skill)
  end

  def keywords
    workers_params[:keywords].split(',') if workers_params[:keywords]
  end

  def render_worker_save(worker, item)
    if worker.save
      render_success(item)
    else
      render_error(worker)
    end
  end

  def render_success(item)
    render(
      text: "Added #{item} to #{current_user.email}!",
      status: 200, layout: false)
  end

  def render_error(worker)
    render(
      text: "Error! #{worker.errors.full_messages}",
      status: 422, layout: false)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def paginate objects, options = {}
    options.reverse_merge!( theme: 'twitter-bootstrap-3' )
    super( objects, options )
  end
end

app/helpers/skills_helper.rb
module SkillsHelper
end

app/views/customer/shared/_links.html.erb
<%- if controller_name != 'sessions' %>
  <%= link_to "Log in", new_session_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.registerable? && controller_name != 'registrations' %>
  <%= link_to "Sign up", new_registration_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.recoverable? && controller_name != 'passwords' && controller_name != 'registrations' %>
  <%= link_to "Forgot your password?", new_password_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.confirmable? && controller_name != 'confirmations' %>
  <%= link_to "Didn't receive confirmation instructions?", new_confirmation_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.lockable? && resource_class.unlock_strategy_enabled?(:email) && controller_name != 'unlocks' %>
  <%= link_to "Didn't receive unlock instructions?", new_unlock_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.omniauthable? %>
  <%- resource_class.omniauth_providers.each do |provider| %>
    <%= link_to "Sign in with #{provider.to_s.titleize}", omniauth_authorize_path(resource_name, provider) %><br />
  <% end -%>
<% end -%>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>SkilledWorker</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
<% if user_signed_in? %>
<div style="float:right;margin-right: 10px;">
    <%= link_to('Logout', destroy_user_session_path, :method => :delete) %>
</div>
<% end %>
<%= yield %>

</body>
</html>

app/views/skills/_customer_skills.js.erb
$("#skills").html("<%= escape_javascript(render 'skills') %>");
$("tr[data-link]").click(function() {
  $("#selected_skills").append(this.dataset.link + ',');
  $("#selected_skills_labels").append(' <span class="label label-info">' + this.dataset.link + '</span> ');
  updateWorkers($("#selected_skills").text());

});

app/views/skills/_default.html.erb
<div id="centre">
  <a href="/workers/sign_in" type="button" class="btn btn-default btn-lg">
    <span class="glyphicon glyphicon-wrench"></span> Login/Signup Worker
  </a>

  <a href="/customers/sign_in"  type="button" class="btn btn-default btn-lg">
    <span class="glyphicon glyphicon-shopping-cart"></span> Login/Signup Customer
  </a>
</div>

app/views/skills/_initial_customers_js.html.erb
<%= javascript_tag  do %>


  $(document).ready(function(){

  $("#skills").html("<%= escape_javascript(render 'skills') %>");

    $("#keywords").keyup(function() {
  console.log('a');
      var form = $(this).parents("form");
      var url = form.attr("action");
      var formData = form.serialize();
      $.get(url, formData, function(html) {
      });
    });

  $("tr[data-link]").click(function() {
  $("#selected_skills").append(this.dataset.link + ',');
  $("#selected_skills_labels").append(' <span class="label label-info">' + this.dataset.link + '</span> ');
    updateWorkers($("#selected_skills").text());

  });

  });

  function updateWorkers(selected_skills){
    $.ajax({
      type: 'GET',
      url: '/workers?keywords=' + selected_skills,
      success: function(data){
        $("#workers").html(data);
      },
      dataType: 'html'
    });
  }


<% end %>

app/views/skills/_initial_workers_js.html.erb
<%= javascript_tag  do %>

  $("#skills").html("<%= escape_javascript(render 'skills') %>");
  $("#keywords").keyup(function () {
  var form = $(this).parents("form");
  var url = form.attr("action");
  var formData = form.serialize();
  $.get(url, formData, function (html) {

  });
  });

  $("tr[data-link]").click(function () {
  $("#selected_skills_labels").append(' <span class="label label-info">' + this.dataset.link + '</span> ');
  updateWorkers(this.dataset.link);
  });


  function updateWorkers(skill_name) {
  $.ajax({
  type: 'GET',
  url: '/workers/skill?skill=' + skill_name,
  success: function (data) {
  $("#workers").html(data);
  }, error: function(data){
  console.log(data);
  $("#workers").html(data.responseText);
  },
  dataType: 'html'
  });
  };


<% end %>

app/views/skills/_skills.html.erb
<table class="table table-striped skills-table">
  <tbody>
  <% @skills.each do |skill| %>
  <tr data-link="<%= skill.name %>">
    <td><%= skill.name %></td>
  </tr>
<% end %>
  </tbody>
</table>
<%= paginate @skills, :remote => true  %>

app/views/skills/_worker_skills.js.erb
$("#skills").html("<%= escape_javascript(render 'skills') %>");

$("tr[data-link]").click(function () {
 $("#selected_skills_labels").append(' <span class="label label-info">' + this.dataset.link + '</span> ');
  updateWorkers(this.dataset.link);
});

app/views/skills/index.html.erb
<% unless current_user.blank? %>

  <%= form_tag({ controller: "skills", action: "search" }, method: "get", remote: true) do %>
    <div class="skill_search">
      <input id="keywords" name="keywords" type="text" autocomplete="off" placeholder="Search skills" class="form-control"/>
    </div>
    <input type=hidden id="selected_skills"/>
    <div id="selected_skills_labels"><a href="javascript:window.location.href=window.location.href">Reset</a></div>
    <p>
    <div id="skills"></div>
    </p>
  <% end %>

  <% if current_customer %>
    <%= render 'initial_customers_js' %>
  <% else %>
    <%= render 'initial_workers_js' %>
  <% end %>

  <div id="workers"></div>

<% else %>
  <%= render 'default' %>
<% end %>

app/views/skills/index.js.erb
<% if current_customer %>
  <%= render 'customer_skills' %>
<% else %>
  <%= render 'worker_skills' %>
<% end %>

app/views/skills/search.js.erb
<% if current_customer %>
  <%= render 'customer_skills' %>
<% else %>
  <%= render 'worker_skills' %>
<% end %>

app/views/worker/shared/_links.html.erb
<%- if controller_name != 'sessions' %>
  <%= link_to "Log in", new_session_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.registerable? && controller_name != 'registrations' %>
  <%= link_to "Sign up", new_registration_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.recoverable? && controller_name != 'passwords' && controller_name != 'registrations' %>
  <%= link_to "Forgot your password?", new_password_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.confirmable? && controller_name != 'confirmations' %>
  <%= link_to "Didn't receive confirmation instructions?", new_confirmation_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.lockable? && resource_class.unlock_strategy_enabled?(:email) && controller_name != 'unlocks' %>
  <%= link_to "Didn't receive unlock instructions?", new_unlock_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.omniauthable? %>
  <%- resource_class.omniauth_providers.each do |provider| %>
    <%= link_to "Sign in with #{provider.to_s.titleize}", omniauth_authorize_path(resource_name, provider) %><br />
  <% end -%>
<% end -%>

app/views/workers/_workers.html.erb
<div>
  <% @workers.each do |worker| %>
  <span class="worker-box">
    <div class="worker_img">
      <%= image_tag worker.image_url %>
    </div>
    <%= worker.email %>
    <br>
    <% worker.skills.each do |skill| %>
      <span class="label label-info" style="margin-right: 2px;">
        <%= skill.name %>
      </span>
    <% end %>
    <div style="margin-top: 5px;" data-no-turbolink>
      <a href="<%= workers_customer_path(worker.id) %>" class="btn btn-primary" type="button">
        Hire! <span class="badge"> <%= worker.customers.count %> </span>
      </a>
    </div>
  </span>
  <% end %>
  <br>
  <%= paginate @workers, param_name: 'workers_page', :remote => true %>
</div>

app/views/workers/index.html.erb
<%= render 'workers' %>

app/views/workers/index.js.erb
$("#workers").html("<%= escape_javascript(render 'workers') %>");